### ISSUE TITLE
Error in log "using state class 'measurement' which is impossible"

### ISSUE THREAD

**Issue by chicagoandy** [mletenay/home-assistant-tigo#2]
Thanks for pulling together this integration.

I'm getting the following error in my logs for each TS4.

Entity sensor.panel_d7_bypass (<class 'custom_components.tigo.sensor.TigoSensorEntity'>) is using state class 'measurement' which is impossible considering device class ('enum') it is using; expected None; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/mletenay/home-assistant-tigo/issues

**Comment by mletenay** [comment]
Thanks.
I'm considering removing that sensor completely and replace it by generic status.
I figured bit 6 of it is pane on/off, just need to figure out which is the bypass

**Comment by mletenay** [comment]
So I replaced it with numeric status entity, without human readable label yet.
Plus FYI - I've just added buttons for turning panels ON/OFF

**Comment by chicagoandy** [comment]
I never understood why turning the panels off wasn't exposed through ei app.    Thanks!
