### ISSUE TITLE
Home Assistant Login issue

### ISSUE THREAD

**Issue by danielegger1** [mletenay/home-assistant-tigo#7]
I used the steps, which did not allowed me to see the Webinterface. I found in the forum a slightly modified echo... line, which then worked properly.
I can not access all webinterfaces with Tigo:$olar password, but I cannot add this to HA, it always states "failed to connect".
When I enter the wrong user / password it adds it to HA and only shows 3 unavailable entities (turn off/on and cca temperature)

What can cause the HA connection to fail?

**Comment by mletenay** [comment]
Enable logging on the integration and attach the log files, I will take a look

**Comment by danielegger1** [comment]
Got it working
Needed a restart of the systems (both) before getting it working
Thanks :)
